//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grocer_Panda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminbd
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<int> contact { get; set; }
        public string address { get; set; }
        public string storeName { get; set; }
    }
}
