//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grocer_Panda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CompanyID { get; set; }
        public string Email { get; set; }
        public string CustomerName { get; set; }
        public string Pasword { get; set; }
        public Nullable<int> Phone_ { get; set; }
        public string city { get; set; }
        public string address { get; set; }
    }
}
